# Generated by Django 3.2.9 on 2021-11-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('emp_code', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=9)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.position')),
            ],
        ),
    ]
